%
% This is part of LFSbookja package.
%
% This is a CTIE change file for the original XML source of the LFSbook.
%
@x
<!-- version info automatically generated by git
@y
<?xml version="1.0" encoding="UTF-8"?>
<!-- version info automatically generated by git
@z

@x
<!--
<!ENTITY version         "10.2-rc1">
<!ENTITY versiond        "10.2-systemd-rc1">
<!ENTITY releasedate     "August 26th, 2021">
<!ENTITY copyrightdate   "1999-2021">
-->
@y
<!--
<!ENTITY version         "10.2-rc1">
<!ENTITY versiond        "10.2-systemd-rc1">
<!ENTITY releasedate     "August 26th, 2021">
<!ENTITY copyrightdate   "1999-2021">
-->
<!ENTITY jversion        "20210915">
<!ENTITY jversiond       "20210915">
<!ENTITY jcorrespondSHA  "007d3bcce"> <!-- lfs-git SHA 値； 本箇所での記載のみ -->
<!ENTITY dir-jversion    "git-ja">
<!ENTITY dir-jversiond   "git-sysdja">
@z

@x
<!ENTITY lfs-root        "https://www.linuxfromscratch.org/">
@y
<!ENTITY lfs-root        "https://www.linuxfromscratch.org/">
<!ENTITY lfs-rootja      "http://lfsbookja.osdn.jp/">
@z

@x
<!ENTITY downloads-root  "&lfs-root;lfs/downloads/&generic-version;/">
@y
<!ENTITY downloads-root  "&lfs-root;lfs/downloads/&generic-version;/">
<!ENTITY download-scripts  "&lfs-rootja;&dir-jversion;/">
@z

% systemd版には lfs-bootscripts が不要なので以下も不要
%@x
%<!ENTITY downloads-rootd "&lfs-root;lfs/downloads/&generic-versiond;/">
%@y
%<!ENTITY downloads-rootd "&lfs-root;lfs/downloads/&generic-versiond;/">
%<!ENTITY download-scriptsd "&lfs-rootja;&dir-jversiond;/">
%@z

@x
<!ENTITY lfs-ticket-root "https://wiki.linuxfromscratch.org/lfs/ticket/">
@y
<!ENTITY lfs-ticket-root "https://wiki.linuxfromscratch.org/lfs/ticket/">
<!ENTITY lfs-changeset   "https://wiki.linuxfromscratch.org/lfs/changeset/">
<!ENTITY lfs-ticket-rootja "https://osdn.net/projects/lfsbookja/ticket/">
<!ENTITY lfs-rev-root    "https://wiki.linuxfromscratch.org/lfs/changeset/">
@z

@x
<!ENTITY buildtime       "Approximate build time">
<!ENTITY diskspace       "Required disk space">
<!ENTITY dependencies    "Installation depends on">
<!ENTITY runtime         "Required at runtime">
<!ENTITY testsuites      "Test suite depends on">
<!ENTITY before          "Must be installed before">
<!ENTITY external        "Optional dependencies">
@y
<!ENTITY buildtime       "概算ビルド時間">
<!ENTITY diskspace       "必要ディスク容量">
<!ENTITY dependencies    "インストール依存パッケージ">
<!ENTITY runtime         "実行時依存パッケージ">
<!ENTITY testsuites      "テストスイート依存パッケージ">
<!ENTITY before          "事前インストールパッケージ">
<!ENTITY external        "任意依存パッケージ">

<!-- Translated words or sentences -->
<!ENTITY InstallationOf1      "">
<!ENTITY InstallationOf2      " のインストール">
<!ENTITY PreparePackage1      "">
<!ENTITY PreparePackage2      " をコンパイルするための準備をします。">
<!ENTITY CompileThePackage    "パッケージをコンパイルします。">
<!ENTITY NotExistTestsuite    "このパッケージにテストスイートはありません。">
<!ENTITY InstallThePackage    "パッケージをインストールします。">
<!ENTITY MeaningOfOption1     "">
<!ENTITY MeaningOfOption2     " オプションの意味">
<!ENTITY MeaningOfParameter1  "">
<!ENTITY MeaningOfParameter2  " パラメーターの意味">
<!ENTITY MeaningOfCommand1    "">
<!ENTITY MeaningOfCommand2    " コマンドの意味">
<!ENTITY Configuring1         "">
<!ENTITY Configuring2         " の設定">
<!ENTITY ContentsOf1          "">
<!ENTITY ContentsOf2          " の構成">
<!ENTITY InstalledProgram     "インストールプログラム">
<!ENTITY InstalledLibrary     "インストールライブラリ">
<!ENTITY InstalledDirectory   "インストールディレクトリ">
<!ENTITY InstalledHeaders     "インストールヘッダー">
<!ENTITY InstalledFiles       "インストールファイル">
<!ENTITY InstalledScripts     "インストールスクリプト">
<!--
      <segtitle>&InstalledProgram;</segtitle>
      <segtitle>&InstalledLibrary;</segtitle>
      <segtitle>&InstalledDirectory;</segtitle>
-->
<!ENTITY ShortDescriptions    "概略説明">
<!ENTITY Details1             "本パッケージの詳細は ">
<!ENTITY Details2             "を参照してください。">

<!ENTITY Homepage             "ホームページ">
<!ENTITY Download             "ダウンロード">
<!ENTITY Tools                "ツール">
@z
